language: cpp
dist: xenial
sudo: required
env:
  - VALGRIND_VERSION=VALGRIND_3_17_0
  - VALGRIND_VERSION=master
matrix:
  allow_failures:
    - env: VALGRIND_VERSION=master
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libc-dbg
install:
  - make -f travis.mk download-valgrind
  - make -f travis.mk patch-valgrind || make -f travis.mk patch-error
  - make -f travis.mk configure
  - make -f travis.mk build
script:
  - make -f travis.mk check-install
  - make -f travis.mk check || make -f travis.mk check-error
  - make -f travis.mk unit-test
